<?php


/**
 * This class adds structure of 'application_has_intent' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Fri Sep 11 12:08:44 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ApplicationHasIntentMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ApplicationHasIntentMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(ApplicationHasIntentPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(ApplicationHasIntentPeer::TABLE_NAME);
		$tMap->setPhpName('ApplicationHasIntent');
		$tMap->setClassname('ApplicationHasIntent');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID_APPLICATION_HAS_INTENT', 'IdApplicationHasIntent', 'INTEGER', true, 11);

		$tMap->addForeignKey('APPLICATION_ID', 'ApplicationId', 'INTEGER', 'application', 'ID_APPLICATION', true, 11);

		$tMap->addForeignKey('INTENT_ID', 'IntentId', 'INTEGER', 'intent', 'ID_INTENT', true, 11);

	} // doBuild()

} // ApplicationHasIntentMapBuilder
