default:
  http_metas:
    content-type: text/html

  metas:
    title:        androidmashup.org - make Android apps understand each other
    description:  a bachelors thesis project..
    #keywords:     symfony, project
    language:     en
    robots:       index, follow

  stylesheets:    [main.css, style.css]

  javascripts:    []

  has_layout:     on
  layout:         layout

