<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2009/09/11 00:04:50

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=mashup;host=localhost',
  'username' => 'www-data',
  'password' => 'www-data',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
